LangeHenrik/SDU-SE-F22

src/main/java/dk/sdu/se_f22/som2/IScoring.java, src/main/java/dk/sdu/se_f22/som2/Scoring.java, src/main/java/dk/sdu/se_f22/som2/Test.java
Added methods in Interface and Scoring class
=> Added Classes and Interface

src/main/java/dk/sdu/se_f22/Bim/src/persistence/IPersistence.java, src/main/java/dk/sdu/se_f22/Bim/src/persistence/Persistence.java, src/main/java/dk/sdu/se_f22/Bim/src/services/IJsonService.java, src/main/java/dk/sdu/se_f22/Bim/src/services/JsonService.java, src/main/java/models/Brand.java
Moved the models package to the Java folder, so everyone can import it in a more simple way.
=> Moved the Models package to Java folder

pom.xml
Tilføjede junit plattform suite og junit params dependencies, så folk har mulighed for at gøre brug af @ Suite osv., som vi lærte :D
=> added junit suite & params dependencies

src/main/java/dk/sdu/se_f22/SortingModule/Range/DBRangeFilterReader.java, src/main/java/dk/sdu/se_f22/SortingModule/Range/ReadRangeFilterInterface.java, src/test/java/dk/sdu/se_f22/SortingModule/Range/DBRangeFilterReaderTest.java
Merging forked github into main github.
=> DBRangeFilterReader Class + Interface. Unit tests. 

src/main/java/dk/sdu/se_f22/sortingmodule/infrastructure/domain/SearchQuery.java, src/main/java/dk/sdu/se_f22/sortingmodule/infrastructure/domain/SortingModule.java, src/main/java/dk/sdu/se_f22/sortingmodule/infrastructure/domain/SortingModuleImpl.java, src/test/java/dk/sdu/se_f22/sortingmodule/infrastructure/domain/SortingModuleImplTest.java
Created SortingModuleImpl from the task SOM-53
https://sdu-se-sem2-grp41.atlassian.net/browse/SOM-53
=> Created SortingModuleImpl from SOM-53

src/main/java/dk/sdu/se_f22/searchmodule/twowaysynonyms/DatabaseOperator.java, src/main/java/dk/sdu/se_f22/searchmodule/twowaysynonyms/TwoWaySynonym.java, src/test/java/dk/sdu/se_f22/searchmodule/twowaysynonyms/TestTwoWaySynonym.java
Updated Interface and added an empty test method for updating group id.
=> Updated Interface

src/main/java/dk/sdu/se_f22/sortingmodule/infrastructure/domain/SearchQuery.java
Created SearchQuery class from SOM-32
https://sdu-se-sem2-grp41.atlassian.net/browse/SOM-32
=> Created SearchQuery class from SOM-32

src/test/java/dk/sdu/se_f22/searchmodule/twowaysynonyms/TestTwoWaySynonym.java
made a test for chekking if groups are created corectly
=> added test method for creating synonym groupd

src/main/java/dk/sdu/se_f22/brandmodule/index/IndexInterface.java, src/main/java/dk/sdu/se_f22/brandmodule/management/services/JsonService.java, src/main/java/dk/sdu/se_f22/productmodule/management/IProductManager.java, src/main/java/dk/sdu/se_f22/productmodule/management/ProductAttribute.java, src/main/java/dk/sdu/se_f22/searchmodule/infrastructure/TokenFiltration.java, src/main/java/dk/sdu/se_f22/sharedlibrary/models/Brand.java, src/main/java/dk/sdu/se_f22/sharedlibrary/models/Product.java, src/main/java/dk/sdu/se_f22/sortingmodule/infrastructure/domain/SortingModule.java, src/main/java/dk/sdu/se_f22/sortingmodule/infrastructure/domain/SortingModuleImpl.java, src/main/java/dk/sdu/se_f22/sortingmodule/scoring/Scoring.java, src/test/java/dk/sdu/se_f22/productmodule/management/ProductAttributeTest.java
Created searchString() method.
Needed before we can send the string to the SEM-1
=> added searchString() method

src/test/java/dk/sdu/se_f22/brandmodule/management/services/JsonServiceTest.java
For some reason our test was gone
=> Bim1: got our test back

src/test/java/dk/sdu/se_f22/searchmodule/twowaysynonyms/TestTwoWaySynonym.java
created createSynonym test
changed (TwoWaySynonym.getInstance()) to operator
=> created createSynonym test

src/test/java/dk/sdu/se_f22/searchmodule/twowaysynonyms/TestTwoWaySynonym.java
Just made a loop for an arraylist of the synonyms we want to delete when the test ends.
=> Added create test

src/main/java/dk/sdu/se_f22/brandmodule/stemming/Stemmer.java, src/main/java/dk/sdu/se_f22/brandmodule/stemming/StemmingUtilities.java, src/main/java/dk/sdu/se_f22/brandmodule/stemming/Word.java, src/test/java/dk/sdu/se_f22/brandmodule/stemming/StemmingUtilitiesTest.java, src/test/java/dk/sdu/se_f22/brandmodule/stemming/WordTest.java
Porter stemming algoritmen er nu fuldt implementeret og kan benyttes. Det eneste der mangler, er muligheden for at tilføje stemming exceptions
=> Full implementation of the porter stemming algorithm with public interface.

src/main/java/dk/sdu/se_f22/searchmodule/misspellings/Misspellings.java
=> Added deleteMisspellings

src/main/java/dk/sdu/se_f22/searchmodule/infrastructure/diagrams/classdiagram.puml
Updated the SEM1-infrastrucutre PUML
=> Updated teh UML-diagram for SEM1-Infrastrucutre

src/main/java/dk/sdu/se_f22/searchmodule/twowaysynonyms/TwoWaySynonym.java
Added the update spelling method
=> added the update spelling method

src/main/java/dk/sdu/se_f22/sharedlibrary/db/database.sql
Added a table StemmingException to the database.sql file. Unsure whether this is to be actually used or if there's another plan, though.
=> Added the StemmingException table to the database file

src/main/java/dk/sdu/se_f22/brandmodule/management/services/IndexingService.java, src/main/java/dk/sdu/se_f22/sharedlibrary/db/SeedDatabase.java
Tilføjet get BrandIndex metode og updateIndexInterval
=> IndexingService Update

src/main/java/dk/sdu/se_f22/sortingmodule/infrastructure/domain/SortingModuleImpl.java
No test since it can only possibly return the desired type (the returned method call returns the same type).
=> Completed subtask som-61

src/main/java/dk/sdu/se_f22/brandmodule/index/BrandIndex.java
Added DBConnection in BrandIndex class
=> Connection

pom.xml, src/main/java/dk/sdu/se_f22/Main.java, src/main/java/dk/sdu/se_f22/sharedlibrary/db/DBConnection.java, src/main/java/dk/sdu/se_f22/sharedlibrary/db/LoggingProvider.java, src/main/java/dk/sdu/se_f22/sharedlibrary/db/database.sql, src/main/java/module-info.java
This PR refactors the DBConnection to use a database connection pool, which makes more efficient use of database resources since connections are reused. This PR also implements a LoggingProvider using Log4J and the new database pool, to make database backed logs.
=> Add connection pool and database backed logging provider

README.md, src/main/java/dk/sdu/se_f22/sharedlibrary/db/DBMigration.java
- Removed silent running of migration, when errors occurs.
- Improved readme
=> Fixed minor errors with database migrations

src/main/java/dk/sdu/se_f22/brandmodule/management/Bim.java, src/main/java/dk/sdu/se_f22/brandmodule/management/IBim.java, src/main/java/dk/sdu/se_f22/sharedlibrary/db/SeedDatabase.java
Tilføjet vores seedDatabasemetode til SeedDatabase.java
TIlføjet en getAllBrands()-metode til vores public interface
=> QOL updates BIM1

src/main/java/dk/sdu/se_f22/brandmodule/infrastructure/BrandInfrastructure.java, src/main/resources/dk/sdu/se_f22/brandmodule/infrastructure/TokenizationParameters.json, src/test/java/dk/sdu/se_f22/brandmodule/infrastructure/BrandInfrastructureTest.java
Might have forgotten to commit the last work
=> Fixing mistakes

src/main/java/dk/sdu/se_f22/searchmodule/infrastructure/DelimiterSettings.java, src/main/java/dk/sdu/se_f22/searchmodule/infrastructure/Tokenizer.java, src/test/java/dk/sdu/se_f22/searchmodule/infrastructure/DelimiterSettingsTest.java, src/test/java/dk/sdu/se_f22/searchmodule/infrastructure/TestSearchModule.java, src/test/java/dk/sdu/se_f22/searchmodule/infrastructure/TokenizationTest.java
Updated to use DBConnection pool in all cases.
Refactored Tokenizer
=> Updated to use DBConnection pool

src/main/java/dk/sdu/se_f22/searchmodule/infrastructure/DelimiterSettings.java, src/main/java/dk/sdu/se_f22/searchmodule/infrastructure/SearchLogger.java, src/main/java/dk/sdu/se_f22/searchmodule/infrastructure/SearchModuleUtils.java, src/main/java/dk/sdu/se_f22/searchmodule/infrastructure/Tokenizer.java, src/test/java/dk/sdu/se_f22/searchmodule/infrastructure/DelimiterSettingsTest.java, src/test/java/dk/sdu/se_f22/searchmodule/infrastructure/TestSearchModule.java
In SwitchToPrettyprinter all simple print statments and e.printStackTrace() has been replaced with logger.log/warn/info
=> Merge SwitchToPrettyprinter (actually logger) into main

src/main/java/dk/sdu/se_f22/brandmodule/management/Bim.java, src/main/java/dk/sdu/se_f22/brandmodule/management/IBim.java, src/main/java/dk/sdu/se_f22/brandmodule/management/persistence/IPersistence.java, src/main/java/dk/sdu/se_f22/brandmodule/management/persistence/Persistence.java, src/test/java/dk/sdu/se_f22/brandmodule/management/BimTest.java, src/test/java/dk/sdu/se_f22/brandmodule/management/persistence/PersistenceTest.java, src/test/java/dk/sdu/se_f22/brandmodule/management/services/IndexingServiceTest.java
Finishing tests for BIM 1
//Need BIM2 to fix their method
=> Finishing tests bim1

.github/workflows/compile-test.yml, .github/workflows/system-test.yml, README.md, pom.xml, src/test/java/dk/sdu/se_f22/brandmodule/management/services/IndexingServiceTest.java
This adds a database to the test runner
=> Create database on test runner

src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/data/Database.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/data/DatabaseInterface.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/FilteredTokens.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/Main.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/SearchClass.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/TokenAccess.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/Tokenizer.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/mockCMSInfra/IMockCMSIndex.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/mockCMSInfra/IMockCMSSearch.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/mockCMSInfra/MockCMSIndex.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/mockCMSInfra/MockCMSInput.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/mockCMSInfra/MockFacade.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/mockCMSInfra/MockIrrW.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/mockCMSInfra/MockStem.java, src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/mockCMSInfra/MockStopW.java, src/test/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/FilteredTokensTest.java, src/test/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/TokenizerTest.java
Reverts LangeHenrik/SDU-SE-F22#198
=> Revert "Cms infrastructure"

src/test/java/dk/sdu/se_f22/brandmodule/management/services/IndexingServiceTest.java
a little oversight on our part
=> Fixed the bug where the test took too long

src/main/java/dk/sdu/se_f22/brandmodule/management/persistence/Persistence.java
This bug was hard to track down, since the code passes the tests, but made our code to fail :)
=> Fix autocommit not getting reset, causing subsequent code to hang

src/main/java/dk/sdu/se_f22/Main.java, src/main/java/dk/sdu/se_f22/brandmodule/management/Bim.java, src/main/java/dk/sdu/se_f22/brandmodule/management/IBim.java, src/main/java/dk/sdu/se_f22/brandmodule/management/services/IIndexingService.java, src/main/java/dk/sdu/se_f22/brandmodule/management/services/IndexingService.java, src/test/java/dk/sdu/se_f22/brandmodule/management/services/IndexingServiceTest.java, src/test/java/dk/sdu/se_f22/brandmodule/management/services/JsonServiceTest.java
=> update and refactored a bit

src/main/java/dk/sdu/se_f22/Main.java, src/main/java/dk/sdu/se_f22/brandmodule/management/Bim.java, src/main/java/dk/sdu/se_f22/brandmodule/management/IBim.java, src/main/java/dk/sdu/se_f22/brandmodule/management/services/IIndexingService.java, src/main/java/dk/sdu/se_f22/brandmodule/management/services/IndexingService.java, src/test/java/dk/sdu/se_f22/brandmodule/management/services/IndexingServiceTest.java, src/test/java/dk/sdu/se_f22/brandmodule/management/services/JsonServiceTest.java
Reverts LangeHenrik/SDU-SE-F22#230
=> Revert "update and refactored a bit"

src/main/java/dk/sdu/se_f22/brandmodule/stemming/ExceptionUtilities.java, src/main/java/dk/sdu/se_f22/brandmodule/stemming/IStemmer.java, src/main/java/dk/sdu/se_f22/brandmodule/stemming/Stemmer.java, src/main/java/dk/sdu/se_f22/brandmodule/stemming/StemmingUtilities.java, src/main/java/dk/sdu/se_f22/brandmodule/stemming/Word.java, src/main/resources/dk/sdu/se_f22/sharedlibrary/db/migrations/2.1_stemmig-exception.sql, src/main/resources/dk/sdu/se_f22/sharedlibrary/db/migrations/3.4_stemming_exceptions.sql, src/main/resources/dk/sdu/se_f22/sharedlibrary/db/migrations/5.2_moved_from_database.sql, src/test/java/dk/sdu/se_f22/brandmodule/stemming/StemmerTest.java
Also reformatted existing code. Sorry about the many lines lmao
=> Added support for adding stemming exceptions to the database

src/main/java/dk/sdu/se_f22/searchmodule/misspellings/Misspellings.java
=> Misspellings spelling mistake
